## Libraries

In [181]:
import tensorflow as tf 
import matplotlib.pyplot as plt 
import pandas as pd 
import  seaborn as sns 


## Data Preprocessing


## Training 

In [184]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


## Validation


In [186]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


In [187]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape) 
    break


tf.Tensor(
[[[[189.75 180.75 173.75]
   [185.   176.   169.  ]
   [194.25 185.25 178.25]
   ...
   [175.75 166.75 159.75]
   [189.5  180.5  173.5 ]
   [174.75 165.75 158.75]]

  [[195.25 186.25 179.25]
   [180.75 171.75 164.75]
   [188.75 179.75 172.75]
   ...
   [193.75 184.75 177.75]
   [172.75 163.75 156.75]
   [187.5  178.5  171.5 ]]

  [[195.25 186.25 179.25]
   [183.5  174.5  167.5 ]
   [184.   175.   168.  ]
   ...
   [165.25 156.25 149.25]
   [175.   166.   159.  ]
   [167.   158.   151.  ]]

  ...

  [[139.25 117.25 106.25]
   [141.75 119.75 108.75]
   [145.75 123.75 112.75]
   ...
   [133.   113.   104.  ]
   [153.   133.   124.  ]
   [138.5  118.5  109.5 ]]

  [[145.75 123.75 112.75]
   [142.5  120.5  109.5 ]
   [154.   132.   121.  ]
   ...
   [150.25 130.25 121.25]
   [143.25 123.25 114.25]
   [138.25 118.25 109.25]]

  [[151.   129.   118.  ]
   [135.25 113.25 102.25]
   [146.75 124.75 113.75]
   ...
   [138.25 118.25 109.25]
   [137.5  117.5  108.5 ]
   [128.5  108.5   9

##  Building Model 


In [189]:
model =tf.keras.models.Sequential()

In [190]:
## Building Convolution Layer 

In [191]:
model.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, padding='same' , activation='relu', input_shape=[128,128,3]))
model.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [192]:
model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, padding='same' , activation='relu', input_shape=[128,128,3]))
model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [193]:
model.add(tf.keras.layers.Conv2D(filters=128, kernel_size=3, padding='same' , activation='relu', input_shape=[128,128,3]))
model.add(tf.keras.layers.Conv2D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [194]:
model.add(tf.keras.layers.Conv2D(filters=256, kernel_size=3, padding='same' , activation='relu', input_shape=[128,128,3]))
model.add(tf.keras.layers.Conv2D(filters=256, kernel_size=3, padding='same', activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [195]:
model.add(tf.keras.layers.Conv2D(filters=512, kernel_size=3, padding='same' , activation='relu', input_shape=[128,128,3]))
model.add(tf.keras.layers.Conv2D(filters=512, kernel_size=3, padding='same', activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [196]:
model.add(tf.keras.layers.Dropout(0.25))

In [197]:
model.add(tf.keras.layers.Flatten())

In [198]:
model.add(tf.keras.layers.Dense(units=1500,activation='relu'))

In [199]:
model.add(tf.keras.layers.Dropout(0.4))

In [200]:
model.add(tf.keras.layers.Dense(units=38,activation='softmax'))

## Compiling Model

In [202]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])


In [203]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_32 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_33 (Conv2D)              │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_16 (MaxPooling2D) │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_34 (Conv2D)              │ (None, 64, 64, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_35 (Conv2D)              │ (None, 64, 64, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_17 (MaxPooling2D) │ (None, 32, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_36 (Conv2D)              │ (None, 32, 32, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_37 (Conv2D)              │ (None, 32, 32, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_18 (MaxPooling2D) │ (None, 16, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_38 (Conv2D)              │ (None, 16, 16, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_39 (Conv2D)              │ (None, 16, 16, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_19 (MaxPooling2D) │ (None, 8, 8, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_40 (Conv2D)              │ (None, 8, 8, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_41 (Conv2D)              │ (None, 8, 8, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_20 (MaxPooling2D) │ (None, 4, 4, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 4, 4, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 8192)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1500)           │    12,289,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,058,762 (65.07 MB)

 Trainable params: 17,058,762 (65.07 MB)

 Non-trainable params: 0 (0.00 B)

In [205]:
training_history = model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10


ValueError: Arguments `target` and `output` must have the same rank (ndim). Received: target.shape=(None,), output.shape=(None, 38)